### ISSUE TITLE
build of index not triggered automatically

### ISSUE THREAD

**Issue by goern** [thoth-station/tensorflow-build-s2i#10]
Builds of https://index-aicoe.a3c1.starter-us-west-1.openshiftapps.com/ are not triggered automatically.

**Comment by harshad16** [comment]
The build triggers automatically through a webhook. The OpenShift Build generic webhook is set up in [AICoE/tensorflow-wheels](https://github.com/AICoE/tensorflow-wheels) repository, whenever a Release or Push is made into the AICoE/repository the OpenShift Build is triggered through generic webhook.

The process was set up by Christoph(@goern ).

As the feature is functional. I m Closing the issue.
