### ISSUE TITLE
wheel files carry linux rather than manylinux1 in filename

### ISSUE THREAD

**Issue by goern** [thoth-station/tensorflow-build-s2i#20]
@fridex

**Comment by fridex** [comment]
Relevant: https://www.python.org/dev/peps/pep-0513/

**Comment by goern** [comment]
@fridex is this still valid?

**Comment by fridex** [comment]
Yes, I can see `linux` instead of manylinux tags:

https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple/tensorflow/

/remove-lifecycle stale
