### ISSUE TITLE
Default source repo should not point to personal fork

### ISSUE THREAD

**Issue by vpavlin** [thoth-station/tensorflow-build-s2i#40]
See https://github.com/thoth-station/tensorflow-build-s2i/blob/master/cuda/cuda-build-chain.yaml#L302

and

https://github.com/thoth-station/tensorflow-build-s2i/blob/master/cuda/cuda-build-chain.yaml#L243

**Comment by harshad16** [comment]
> /cc @harshad16

Thanks, @vpavlin , we will update with the upstream repo.

**Comment by vpavlin** [comment]
Bump:-)
